sudo: false

language: node_js

node_js:
  - "node"

cache:
  directories:
    - $HOME/.meteor
    - $HOME/.npm

notifications:
  email: false
  slack: collinhaines:puhDfkIE5qaclQJKdDwyAPbd

before_install:
  - if [ ! -e $HOME/.meteor/meteor ]; then curl -k https://install.meteor.com | sh; fi
